dartmouth-cs98/18w-si32

worker/bot1/SimpleGameHelper.py
worker/bot1/bot.py
worker/bot_common/SimpleGameHelper.py

With game helper function to give back only those squares which have the current players' units on them.

Sample bot that actually moves down

---

AI/Game.py
AI/Logger.py
AI/Si32_Game.py
AI/requirements.txt
api/app/errors.js
api/app/files/fileMiddleware.js
api/app/files/s3.js
api/app/models/matchModel.js
api/app/routes/workerRoutes.js
api/package-lock.json
api/package.json
worker/endpoints.py
worker/requirements.txt
worker/runSingleGameLocally.py
worker/startLocalWorker.py
worker/startWorker.py
worker/waitForGame.py

- Logger class inside of game to only log things needed and use smaller keys
- msgpack + gzip of log before sending to API server
- uploading of log from API server to S3
resolves #119 
resolves #118 
now ready to do #109

Game logging and uploading

---

web/package.json
web/src/components/replay/Canvas.jsx
web/src/components/replay/ReplayReader.jsx
web/src/components/replay/ReplayVisualizer.jsx

Basic validation of replay files; component now set up to handle the decided upon format. Resolves [#141](https://github.com/dartmouth-cs98/18w-si32/issues/141)

Replay file validation

---

api/app/files/s3.js
api/app/models/matchModel.js
api/app/routes/matchRoutes.js
api/app/routes/workerRoutes.js
web/package-lock.json
web/package.json
web/src/components/matches/singlePage.jsx
web/src/data/bot/botActions.js
web/src/data/match/matchActions.js
web/src/data/match/matchRoutes.js
web/src/data/user/userActions.js

resolves #77 
resolves #109 
@kyledotterrer everything's all hooked up and ready for viz now!

Single match endpoint and retrieve game logs

---

web/src/components/common/progress.jsx
web/src/components/replay/Canvas.jsx
web/src/components/replay/ReplayReader.jsx
web/src/components/replay/ReplayVisualizer.jsx
web/src/style/constants.js

Current limitations:
* not doing smart transitions (i.e. not taking individual commands into account yet)
* set up statically to handle 2 players --> not generalized

Replays reading from game log files

---

api/app/errors.js
api/app/files/s3.js
api/app/index.js
api/app/models/matchModel.js
api/app/routes/botRoutes.js
api/app/routes/userRoutes.js
web/src/components/bots/createPage.jsx
web/src/components/common/button.jsx
web/src/components/common/message.jsx
web/src/components/matches/createPage.jsx
web/src/components/user/loginPage.jsx
web/src/components/user/registerPage.jsx
web/src/data/bot/botActions.js
web/src/data/httpCollectionActions.js

fixes #153 (though just passes through the raw mongoose/mongo error) and adds basic error handling/display for the user across bot, match, login, and register forms

Error messaging

---

web/src/components/bots/BotCard.jsx
web/src/components/common/statDifference.jsx
web/src/components/dashboard/HeaderStatsBar.jsx
web/src/components/dashboard/dashboardPage.jsx
web/src/components/matches/singlePage.jsx
web/src/components/replay/ReplayVisualizer.jsx

resolves #150 (party, opened #165 for remainder)

Wire rating history into dashboard

---

api/app/routes/leaderboardQueries.js
api/app/routes/matchRoutes.js
web/src/components/bots/BotCard.jsx
web/src/components/dashboard/HeaderStatsBar.jsx
web/src/components/dashboard/dashboardPage.jsx
web/src/components/groups/GroupList.jsx
web/src/components/groups/singlePage.jsx
web/src/components/leaderboard/leaderboardPage.jsx
web/src/components/matches/singlePage.jsx
web/src/components/user/profilePage.jsx

resolves #165 
attaches how many people the ranking is out of for rank queries

Update rank queries to return count

---

web/src/components/dashboard/HeaderStatsBar.jsx
web/src/components/replay/ReplayVisualizer.jsx
web/src/components/replay/replayPage.jsx

Resolves [#170](https://github.com/dartmouth-cs98/18w-si32/issues/170)

add ability to select a new file when on replay viz page

---

web/src/components/dashboard/dashboardPage.jsx
web/src/components/dashboard/userSearch.jsx

Resolves [#173](https://github.com/dartmouth-cs98/18w-si32/issues/173)

towards a more consistent appearance

---

web/src/components/dashboard/dashboardPage.jsx
web/src/components/matches/MatchList.jsx
web/src/data/match/matchSelectors.js

Basic match list UI

---

web/src/config.prod.js

Resolves [#204](https://github.com/dartmouth-cs98/18w-si32/issues/204)
Interesting issue, fix found [here](https://www.ecenica.com/support/answer/redirect-all-domains-to-https-domain/).

Fix SSL issue 

---

api/.eslintrc.json
web/src/components/common/button.jsx
web/src/components/groups/GroupList.jsx
web/src/components/matches/MatchList.jsx
web/src/components/user/profilePage.jsx

Profile UI

---

web/src/store.js

clear store on logout

---

game/Building.py
game/Command.py
game/Game.py
game/Logger.py
game/Map.py
game/Player.py
game/Rules.py
game/Si32_Game.py
game/Tile.py
game/json_helpers.py
game/params.py

Resolves [#139](https://github.com/dartmouth-cs98/18w-si32/issues/139)

Magic numbers

---

api/app/models/botModel.js
api/app/routes/botRoutes.js

Store bot version history

---

game/Rules.py

Reverts dartmouth-cs98/18w-si32#245

Revert "Paul d"

---

api/app/routes/botRoutes.js
web/package-lock.json
web/package.json
web/src/components/matches/createPage.jsx

Bot selection on match create page

---

api/app/routes/botRoutes.js
web/package-lock.json
web/package.json
web/src/components/bots/singlePage.jsx
web/src/components/common/SkillHistoryChart.jsx
web/src/components/matches/singlePage.jsx
web/src/components/user/profilePage.jsx

Basic charts

---

web/src/components/matches/createPage.jsx

Choose multiple bots while creating match

---

web/package-lock.json
web/package.json
web/src/app.jsx
worker/package-lock.json

Use babel polyfill to handle other browsers

---

web/src/components/matches/singlePage.jsx
web/src/components/replay/Canvas.jsx
web/src/store.js
worker/start.sh

also have worker handle up to 4 bots
resolves #179

Color player name in match page by which bot they are

---

web/src/components/matches/singlePage.jsx

Add loading message for game replay

---

game/Building.py
game/Cell.py
game/Logger.py
game/Map.py
web/src/components/common/progress.jsx
web/src/components/replay/Canvas.jsx
web/src/components/replay/ReplayVisualizer.jsx
worker/bot_common/GameHelper.py

Fix game, add cell numbers, add scrub on progress bar

---

web/src/components/matches/singlePage.jsx
web/src/components/replay/CellDetails.jsx
web/src/components/replay/GameStats.jsx

Game stats

---

.gitignore
api/package.json
docs/package.json
internal/README.md
internal/package.json
internal/requirements.txt
web/package.json

Resolves [#319](https://github.com/dartmouth-cs98/18w-si32/issues/319)

Automation of asset management

---

devkit/train.py
devkit/train.sh
game/GameState.py
game/Player.py

Resolves [#307](https://github.com/dartmouth-cs98/18w-si32/issues/307)

training script added to devkit 

---

game/Bot.py
game/Cell.py
game/DockerBot.py
game/GameState.py
game/Map.py
game/Rules.py
game/params.py

Resolves [#327](https://github.com/dartmouth-cs98/18w-si32/issues/327)
Resolves [#164](https://github.com/dartmouth-cs98/18w-si32/issues/164) (because I realized we already have this, although we should document it somewhere?)

fix up imports

---

api/app/models/matchModel.js
api/app/routes/matchRoutes.js
web/src/components/matches/MatchList.jsx
web/src/components/matches/singlePage.jsx

resolves #253 
resolves #226 
resolves #64

Automatically create matches

---

api/.env.example
api/app/files/s3.js

Use different s3 buckets for local vs live

---

web/src/components/layout/navigation.jsx
web/src/config.dev.js
web/src/config.prod.js

Resolves [#225](https://github.com/dartmouth-cs98/18w-si32/issues/225)

Built in feedback on client 

---

api/app/lib/trueskill.js
api/app/routes/botRoutes.js

adjust user/bot sigmas on new uploads

---

api/app/routes/userRoutes.js
web/src/components/user/registerPage.jsx
web/src/config.dev.js
web/src/config.prod.js

Resolves [#334](https://github.com/dartmouth-cs98/18w-si32/issues/334)
Resolves [#277](https://github.com/dartmouth-cs98/18w-si32/issues/277)

Updates to registration

---

web/src/components/landing/LandingCanvas.jsx
web/src/components/user/registerPage.jsx

Reverts dartmouth-cs98/18w-si32#348

Revert "Hex"

---

docs/api-reference/README.md
docs/game-rules/README.md
docs/getting-started/README.md
docs/introduction.md
game/Cell.py
game/Game.py
game/Hive.py
game/Logger.py
game/Player.py
game/README.md
game/Rules.py
game/params.py
sample_bots/fortifier/bot.py
visualizer/src/components/Canvas.jsx
web/src/components/replay/Canvas.jsx
web/src/components/replay/GameStats.jsx
worker/bot_common/GameHelper.py

Resolves [#341](https://github.com/dartmouth-cs98/18w-si32/issues/341)

Refactor buildings --> hives

---

api/package.json
game/Cell.py
game/Logger.py
game/Map.py
web/package-lock.json
web/src/components/replay/Canvas.jsx

Resolves [#298](https://github.com/dartmouth-cs98/18w-si32/issues/298)

Support for obstacles in logfile and viz

---

api/package-lock.json
game/Cell.py
game/Game.py
game/Logger.py
game/Map.py
game/ObstacleMapProblem.py
game/Rules.py
worker/bot_common/GameHelper.py

Resolves [#375](https://github.com/dartmouth-cs98/18w-si32/issues/375)
Resolves [#377](https://github.com/dartmouth-cs98/18w-si32/issues/377)

Obstacle fixes and proof of concept for deterministic maps 

---

game/Cell.py

Fix cell update from msgpack

---

web/src/components/replay/ReplayReader.jsx

Resolves [#403](https://github.com/dartmouth-cs98/18w-si32/issues/403)

add replay page explanation

---

web/src/components/dashboard/userSearch.jsx

resolves [#405](https://github.com/dartmouth-cs98/18w-si32/issues/405)

quick update to user search

---

api/app/auth.js
api/app/files/s3.js
api/app/routes/matchRoutes.js
web/src/components/common/button.jsx
web/src/components/landing/landingPage.jsx
web/src/components/matches/singlePage.jsx
web/src/components/replay/Canvas.jsx
web/src/components/user/loginPage.jsx
web/src/components/user/registerPage.jsx
web/src/data/httpCollectionActions.js
web/src/data/match/matchActions.js
web/src/style/constants.js
web/webpack.common.js

Resolves [#396](https://github.com/dartmouth-cs98/18w-si32/issues/396)

Landing page improvements

---

docs/downloads/README.md
docs/sample/README.md
internal/package.json
internal/scripts-sample/sample-cp.sh
internal/scripts-sample/sample-zip.sh

Resolves [#413](https://github.com/dartmouth-cs98/18w-si32/issues/413)

Sample bots ready to go, automated re-uploads 

---

internal/README.md
internal/package.json
internal/requirements.txt
internal/scripts-sample/sample-clean.sh
internal/scripts-sample/sample-obfuscate.sh
internal/scripts-sample/sample-zip.sh
sample/random/bot.py

Done in a pretty rudimentary way that is (mostly) reversible, but nonetheless should discourage some from copying code. 
Resolves [#421](https://github.com/dartmouth-cs98/18w-si32/issues/421)

Obfuscate the source for sample bots 

---

web/src/components/dashboard/dashboardPage.jsx
web/src/components/layout/footer.jsx
web/src/components/leaderboard/LeaderboardTable.jsx
web/src/components/leaderboard/leaderboardPage.jsx
web/src/components/matches/MatchList.jsx
web/src/components/matches/listPage.jsx
web/src/data/match/matchSelectors.js

resolves #256 
resolves #361 
resolves #219

dashboard, group, and other general UI improvements

---

docs/SUMMARY.md
docs/getting-started/devkit.md
docs/introduction.md
docs/strategies/README.md
internal/README.md
internal/package.json
web/src/components/landing/landingPage.jsx

Resolves [#418](https://github.com/dartmouth-cs98/18w-si32/issues/418)
Resolves [#395](https://github.com/dartmouth-cs98/18w-si32/issues/395)

Minor improvements
